USE [master]
GO

/****** Object:  Database [ImagesStoreSystem]    Script Date: 02/04/2010 18:01:16 ******/
CREATE DATABASE [ImagesStoreSystem] ON  PRIMARY 
( NAME = N'ImagesStoreSystem', FILENAME = N'C:\Work\DB\MSSQL\ImagesStoreSystem.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
 FILEGROUP [STATIC] 
( NAME = N'ImagesStoreSystem_static', FILENAME = N'C:\Work\DB\MSSQL\ImagesStoreSystem_static.ndf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [STREAM] CONTAINS FILESTREAM  DEFAULT 
( NAME = N'ImagesStoreSystem_fs', FILENAME = N'C:\Work\DB\MSSQL\ImagesStoreSystem_fs' )
 LOG ON 
( NAME = N'ImagesStoreSystem_log', FILENAME = N'C:\Work\DB\MSSQL\ImagesStoreSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ImagesStoreSystem] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ImagesStoreSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ImagesStoreSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ImagesStoreSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ImagesStoreSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ImagesStoreSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ImagesStoreSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ImagesStoreSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ImagesStoreSystem] SET  READ_WRITE 
GO

ALTER DATABASE [ImagesStoreSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [ImagesStoreSystem] SET  MULTI_USER 
GO

ALTER DATABASE [ImagesStoreSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ImagesStoreSystem] SET DB_CHAINING OFF 
GO


